Efaas Version: 
cb54e432bd9cce0b095ca599a569dceee89a23e4
iluvatar-energy-experiments Version: 
ab024416bf789b92bb10f3fa63b925281437b79a

PLAY [workers] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [worker1]

TASK [Get running worker process] **********************************************
changed: [worker1]

TASK [debug print] *************************************************************
ok: [worker1] => {
    "msg": "149.159.200.89"
}

TASK [Kill running worker process on localhost] ********************************

TASK [Kill running worker process distrib] *************************************

TASK [Create bin directory] ****************************************************
ok: [worker1]

TASK [copy worker executable] **************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [worker1]: FAILED! => {"changed": false, "msg": "Could not find or access '/data2/ar/efaas/src/Ilúvatar/ansible/../target/release/ilúvatar_worker' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP *********************************************************************
worker1                    : ok=4    changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0   

IGPM logging started
image_processing-0 mapped to function 'image_processing'
dd-0 mapped to function 'dd'
model_training-0 mapped to function 'model_training'
A total of 0 prewarmed containers
2023-07-07 18:11:59.769250301 prewarming Some(0) containers for function 'image_processing-0'
2023-07-07 18:11:59.769488722 prewarming Some(0) containers for function 'dd-0'
2023-07-07 18:11:59.769650323 prewarming Some(0) containers for function 'model_training-0'
2023-07-07 18:11:59.770731356 starting live trace run

PLAY [workers] *****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [worker1]

TASK [Get running worker process] **********************************************
changed: [worker1]

TASK [debug print] *************************************************************
ok: [worker1] => {
    "msg": "149.159.200.89"
}

TASK [Kill running worker process on localhost] ********************************
skipping: [worker1] => (item=88762) 
skipping: [worker1] => (item=88763) 

TASK [Kill running worker process distrib] *************************************
changed: [worker1] => (item=88762)
changed: [worker1] => (item=88763)

TASK [Create bin directory] ****************************************************
ok: [worker1]

TASK [copy worker executable] **************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [worker1]: FAILED! => {"changed": false, "msg": "Could not find or access '/data2/ar/efaas/src/Ilúvatar/ansible/../target/release/ilúvatar_worker' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP *********************************************************************
worker1                    : ok=5    changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

Starting analysis
+ TARGET_BASE=./
+ TRACE_NAME=trace
++ pwd
+ CUR_DIR=/data2/ar/iluvatar-energy-experiments/scripts/experiments/jetson/traced
+ BASE_DIR=/data2/ar/iluvatar-energy-experiments
+ for i in "$@"
+ case $i in
+ TARGET_BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/
+ for i in "$@"
+ case $i in
+ TRACE_NAME=mc_p
++ dirname_uptill /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/ trace
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/
++ TARGET=trace
++ to_return=
++ [[ -n 1==1 ]]
++ last=
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/
++ cur=12
++ [[ 12 == \t\r\a\c\e ]]
++ [[ 12 == \/ ]]
++ to_return=12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12
++ [[ -n 1==1 ]]
++ last=12
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12
++ cur=12
++ [[ 12 == \t\r\a\c\e ]]
++ [[ 12 == \/ ]]
++ to_return=12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs
++ [[ -n 1==1 ]]
++ last=12
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs
++ cur=fcfs
++ [[ fcfs == \t\r\a\c\e ]]
++ [[ fcfs == \/ ]]
++ to_return=fcfs/12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions
++ [[ -n 1==1 ]]
++ last=fcfs
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions
++ cur=functions
++ [[ functions == \t\r\a\c\e ]]
++ [[ functions == \/ ]]
++ to_return=functions/fcfs/12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p
++ [[ -n 1==1 ]]
++ last=functions
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p
++ cur=mc_p
++ [[ mc_p == \t\r\a\c\e ]]
++ [[ mc_p == \/ ]]
++ to_return=mc_p/functions/fcfs/12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm
++ [[ -n 1==1 ]]
++ last=mc_p
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm
++ cur=mc_4f_traces_ddpm
++ [[ mc_4f_traces_ddpm == \t\r\a\c\e ]]
++ [[ mc_4f_traces_ddpm == \/ ]]
++ to_return=mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//.
++ [[ -n 1==1 ]]
++ last=mc_4f_traces_ddpm
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson//.
++ cur=.
++ [[ . == \t\r\a\c\e ]]
++ [[ . == \/ ]]
++ to_return=./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson//.
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace/jetson
++ [[ -n 1==1 ]]
++ last=.
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace/jetson
++ cur=jetson
++ [[ jetson == \t\r\a\c\e ]]
++ [[ jetson == \/ ]]
++ to_return=jetson/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
+++ dirname /data2/ar/iluvatar-energy-experiments/results/trace/jetson
++ BASE=/data2/ar/iluvatar-energy-experiments/results/trace
++ [[ -n 1==1 ]]
++ last=jetson
+++ basename /data2/ar/iluvatar-energy-experiments/results/trace
++ cur=trace
++ [[ trace == \t\r\a\c\e ]]
++ break
++ echo jetson/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
+ TARGET_PLATFORM=jetson/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
++ dirname_front jetson/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
++ s=jetson/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
+++ expr index jetson/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/ /
++ i=7
++ [[ i != 0 ]]
++ i=6
++ s_r=/./mc_4f_traces_ddpm/mc_p/functions/fcfs/12/12/
++ s=jetson
++ echo jetson
+ TARGET_PLATFORM=jetson
+ echo 10000
+ python3 /data2/ar/efaas//src/load/analysis/parse_logs.py -l /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/ -m /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//dummy_max_rapl.txt
Traceback (most recent call last):
  File "/data2/ar/efaas//src/load/analysis/parse_logs.py", line 151, in <module>
    prepare_energy_log(args)
  File "/data2/ar/efaas//src/load/analysis/parse_logs.py", line 130, in prepare_energy_log
    data["hw_cpu_hz_mean"] = np.mean(json_log["hardware_cpu_freqs"])
KeyError: 'hardware_cpu_freqs'
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/analysis/results/Gen_DFs.py -d /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/ -m desk
Traceback (most recent call last):
  File "/data2/ar/iluvatar-energy-experiments/scripts/analysis/results/Gen_DFs.py", line 27, in <module>
    lg.process_all_logs()
  File "/data2/ar/iluvatar-perf22/scripts/experiments/victor/plotting/Logs_to_df.py", line 360, in process_all_logs
    self.worker_log_to_df()
  File "/data2/ar/iluvatar-perf22/scripts/experiments/victor/plotting/Logs_to_df.py", line 176, in worker_log_to_df
    cpu_freq_mean = np.array(status["kernel_cpu_freqs"]).mean()
KeyError: 'kernel_cpu_freqs'
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/analysis/results/parse_function_map.py -l /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//orchestration.log
+ '[' -f /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//tegrastats.log ']'
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/analysis/results/parse_tegrastats.py --log /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//tegrastats.log
+ '[' -f /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//igpm.log ']'
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/analysis/results/plot_igpm_against_tegrastats.py --tlog /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//tegrastats.csv --ilog /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//igpm.log
+ cd /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12/
+ mkdir -p igpm_plots
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/igpm/plot_log.py -l ./igpm.log
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/analysis/results/responsetime_distribution.py
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/status_plot.py -l ./
+ python3 /data2/ar/iluvatar-energy-experiments/faasmeter/stacked_kf_plot.py -l ./ -t desk -o stacked_kf_plot.png -c pulse
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/plot_queueing.py -l ./worker_worker1.log -c ./output-mc_p.csv
+ tmp_so=/tmp/sensor_output
+ tmp_fo=/tmp/formula_output
+ sw_result=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output/
+ mkdir -p /tmp/sensor_output
+ python3 /data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/plot_e2etime.py -c ./output-mc_p.csv
+ mkdir -p /tmp/formula_output
+ cp '/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//sensor_output/*' /tmp/sensor_output/
cp: cannot stat '/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//sensor_output/*': No such file or directory
+ /data2/ar/smartwatts-formula/run_formula.sh -p=jetson
+ for i in "$@"
+ case $i in
+ TARGET_PLATFORM=jetson
+ rm '/tmp/formula_output/*' -rf
+ cd /data2/ar/smartwatts-formula
+ sudo chmod a+wr '/tmp/sensor_output/*'
chmod: cannot access '/tmp/sensor_output/*': No such file or directory
+ python3 -m smartwatts --name formula_smarwatts powerapi/smartwatts-formula --config-file /data2/ar/powerapi_personal/config_formula_smartwatts_jetson.json
Traceback (most recent call last):
  File "/data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/plot_queueing.py", line 1, in <module>
    from queueing import calc_queue_times
  File "/data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/queueing.py", line 6, in <module>
    from Logs_to_df import Logs_to_df
ModuleNotFoundError: No module named 'Logs_to_df'
Traceback (most recent call last):
  File "/data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/plot_e2etime.py", line 1, in <module>
    from queueing import calc_queue_times
  File "/data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/queueing.py", line 6, in <module>
    from Logs_to_df import Logs_to_df
ModuleNotFoundError: No module named 'Logs_to_df'
ERROR:root:Configuration Error: configuration file not found
+ rm -r /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output/
rm: cannot remove '/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output/': No such file or directory
+ mkdir -p /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output/
+ cp /tmp/formula_output /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output// -r
+ /data2/ar/iluvatar-energy-experiments/scripts/smartwatts/concat_powerreports.sh -d=/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-/
/data2/ar/iluvatar-energy-experiments/scripts/smartwatts/concat_powerreports.sh: line 25: /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-//smartwatts_powerreport.csv: No such file or directory
cat: '/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-//*//PowerReport.csv': No such file or directory
/data2/ar/iluvatar-energy-experiments/scripts/smartwatts/concat_powerreports.sh: line 28: /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-//smartwatts_powerreport.csv: No such file or directory
cat: '/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-//*//PowerReport.csv': No such file or directory
+ mv /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-/smartwatts_powerreport.csv /data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//
mv: cannot stat '/data2/ar/iluvatar-energy-experiments/results/trace/jetson//./mc_4f_traces_ddpm/mc_p//functions/fcfs/12/12//smartwatt_output//formula_output/sensor-/smartwatts_powerreport.csv': No such file or directory
+ rm /tmp/sensor_output -rf
+ rm /tmp/formula_output -rf
++ jobs -p
+ wait 4092773 4092775 4092777 4092779
+ mv igpm_i.png igpm_pf.png igpm_p.png igpm_v.png ./igpm_plots/
Traceback (most recent call last):
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/stacked_kf_plot.py", line 172, in <module>
    stack_plot(
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/stacked_kf_plot.py", line 25, in stack_plot
    edata = Logs_to_df(logs_folder, mc_type, output_type='indiv')
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 176, in __init__
    self.populate_system_settings()
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 232, in populate_system_settings
    self.cpu_shr_config( use_default=self.mc_type )
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 1816, in cpu_shr_config
    sw_config['cfeatures'] = cfeatures
UnboundLocalError: local variable 'cfeatures' referenced before assignment
Traceback (most recent call last):
  File "/data2/ar/iluvatar-energy-experiments/scripts/experiments/victor/plotting/status_plot.py", line 37, in <module>
    ldf.process_all_logs()
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 747, in process_all_logs
    self.igpm_to_df()
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 539, in igpm_to_df
    self.Widle = self.get_idle( idf, 'igpm' )
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 468, in get_idle
    nidf = self.normalize_time_df_to_first_invoke( idf.copy() )
  File "/data2/ar/iluvatar-energy-experiments/faasmeter/Logs_to_df.py", line 707, in normalize_time_df_to_first_invoke
    earliest_time = min([self.status_df.index[0], self.proc_df.index[0]])
AttributeError: 'NoneType' object has no attribute 'index'
+ cd /data2/ar/iluvatar-energy-experiments/scripts/experiments/jetson/traced

real	0m9.049s
user	0m27.145s
sys	0m18.948s
